# netlify.toml
# Basic configuration for Netlify deployment

[build]
  command = "npm run build"
  publish = "dist"
  ignore_missing_publish_directory = true

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200